name : "codebhaiya"
services:
  db:
    image: postgres:alpine
    container_name: codebhaiya_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: codebhaiya
      POSTGRES_PASSWORD: codebhaiya
      POSTGRES_DB: codebhaiya
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local
